F: 8 #L96 forcing parameter
T: 100 #max time in model units
N: 40 #number of L96 variables
dt: 0.005 #Assimilation time step
frac: 1 #Fraction of variables observed
nens: 100 #Ensemble size
loc: 7 #Localization factor
localization_method: 'original' #one of "original" or "gc"
gamma: 1.1 #Covariance inflation
r: 0.3 #Observation error standard deviation, fraction of climatological standard deviation
name: 's9' #run name
